title: Nick Miller
description: >- # this means to ignore newlines until "baseurl:"
  Hi there.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nickmiller.dev" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Nick Miller
  email: "mail@nickmiller.dev"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag


remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    github:  nickjmiller
    twitter: nickmillerdev
    linkedin: nick-j-miller
    mastodon:
      - username: nick
        instance: mastodon.nickmiller.dev

show_excerpts: true

exclude:
  - README
  - Gemfile
  - Gemfile.lock
  - CNAME