title: Nick Miller
email: mail@nickmiller.dev
description: >- # this means to ignore newlines until "baseurl:"
  I'm testing out Jekyll and github pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://me.nickmiller.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nickjmiller

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise", "default"

author:
  name             : "Nick Miller"
  avatar           : assets/images/nick.jpg
  bio              : "Hello"
  location         : "Denver, CO"
  email            : mail@nickmiller.dev
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nickjmiller"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

exclude:
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - README
